#define TEXT_MESSAGE_FLAG 0
#define SEND_FILE_FLAG 1
#define RECV_FILE_FLAG 2
#define MAX_BUFFER_SIZE 1024
#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 12345
#define FILE_PATH "./video.mp4"
#define RECEIVED_FILE_PATH "recv.mp4"
#define MAX_CLIENTS 2
#define NUM_THREADS 5
